# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Justin Kaldenbach

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Justin Kaldenbach

description: Tinkerer
author:
  name: Justin Kaldenbach
  github: jkaldenbach
  twitter: jmkaldenbach
  linkedin: jkaldenbach
  bio: Habitual tinkerer
  email_md5: 4120a0884e721211d58f32240ffae101

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
